export const paths = {
  landing: "/",
  login: "/login",
  signup: "/signup",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  dashboard: "/dashboard",
  profile: "/profile",
  notes: "/notes",
  noteNew: "/notes/new",
  noteDetail: (noteId: string) => `/notes/${noteId}`,
  noteEdit: (noteId: string) => `/notes/${noteId}/edit`,
  discussions: "/discussions",
  discussionQuestionNew: "/discussions/questions/new",
  discussionQuestion: (questionId: string) =>
    `/discussions/questions/${questionId}`,
  discussionQuestionEdit: (questionId: string) =>
    `/discussions/questions/${questionId}/edit`,
  marketplace: "/marketplace",
  marketplaceNew: "/marketplace/new",
  marketplaceDetail: (listingId: string) => `/marketplace/${listingId}`,
  marketplaceEdit: (listingId: string) =>
    `/marketplace/${listingId}/edit`,
  internships: "/internships",
  internshipNew: "/internships/new",
  internshipDetail: (internshipId: string) =>
    `/internships/${internshipId}`,
  internshipEdit: (internshipId: string) =>
    `/internships/${internshipId}/edit`,
  events: "/events",
  eventNew: "/events/new",
  eventDetail: (eventId: string) => `/events/${eventId}`,
  eventEdit: (eventId: string) => `/events/${eventId}/edit`,
  notifications: "/notifications",
  search: "/search",
  leaderboard: "/leaderboard",
  assistant: "/ai",
  admin: "/admin",
  settings: "/settings",
} as const;
