export const paths = {
  landing: "/",
  login: "/login",
  signup: "/signup",
  dashboard: "/dashboard",
  profile: "/profile",
  notes: "/notes",
  noteNew: "/notes/new",
  noteDetail: (noteId: string) => `/notes/${noteId}`,
  noteEdit: (noteId: string) => `/notes/${noteId}/edit`,
  discussions: "/discussions",
  marketplace: "/marketplace",
  marketplaceNew: "/marketplace/new",
  marketplaceDetail: (listingId: string) => `/marketplace/${listingId}`,
  marketplaceEdit: (listingId: string) =>
    `/marketplace/${listingId}/edit`,
  internships: "/internships",
  events: "/events",
  notifications: "/notifications",
  search: "/search",
  leaderboard: "/leaderboard",
  assistant: "/ai-assistant",
  admin: "/admin",
  settings: "/settings",
} as const;
