package com.campusone.gamification.entity;

public enum GamificationActionType {
    PROFILE_COMPLETED,
    NOTE_CREATED,
    NOTE_DOWNLOADED,
    NOTE_RATED,
    MARKETPLACE_LISTING_CREATED,
    DISCUSSION_QUESTION_CREATED,
    DISCUSSION_ANSWER_CREATED,
    DISCUSSION_ANSWER_ACCEPTED,
    EVENT_CREATED,
    EVENT_JOINED,
    INTERNSHIP_CREATED,
    DAILY_LOGIN,
    SYSTEM_AWARD
}
